<a href="https://colab.research.google.com/github/hamednasr/transformers/blob/main/tokenizer_and_models.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip -q install transformers

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.7/7.7 MB 20.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 302.0/302.0 kB 31.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.8/3.8 MB 44.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 47.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 295.0/295.0 kB 29.8 MB/s eta 0:00:00


In [2]:
from transformers import AutoTokenizer

In [3]:
checkpoint = 'bert-base-uncased'
tokenizer = AutoTokenizer.from_pretrained(checkpoint)

In [4]:
tokenizer

Using bos_token, but it is not set yet.
Using eos_token, but it is not set yet.


BertTokenizerFast(name_or_path='bert-base-uncased', vocab_size=30522, model_max_length=512, is_fast=True, padding_side='right', truncation_side='right', special_tokens={'unk_token': '[UNK]', 'sep_token': '[SEP]', 'pad_token': '[PAD]', 'cls_token': '[CLS]', 'mask_token': '[MASK]'}, clean_up_tokenization_spaces=True),  added_tokens_decoder={
	0: AddedToken("[PAD]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	100: AddedToken("[UNK]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	101: AddedToken("[CLS]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	102: AddedToken("[SEP]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	103: AddedToken("[MASK]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
}

In [5]:
tokenizer('hello world')

{'input_ids': [101, 7592, 2088, 102], 'token_type_ids': [0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1]}

In [ ]:
#optional
tokens = tokenizer.tokenize('hello world')
tokens

['hello', 'world']

In [ ]:
#optional
tokenizer.convert_tokens_to_ids(tokens)

[7592, 2088]

In [ ]:
#optional
ids = tokenizer.encode('hello world')
ids

[101, 7592, 2088, 102]

In [ ]:
#optional
tokenizer.convert_ids_to_tokens(ids)

['[CLS]', 'hello', 'world', '[SEP]']

In [ ]:
#optional
tokenizer.decode(ids)

'[CLS] hello world [SEP]'

In [ ]:
tokenizer('hello world', return_tensors='tf')

{'input_ids': <tf.Tensor: shape=(1, 4), dtype=int32, numpy=array([[ 101, 7592, 2088,  102]], dtype=int32)>, 'token_type_ids': <tf.Tensor: shape=(1, 4), dtype=int32, numpy=array([[0, 0, 0, 0]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(1, 4), dtype=int32, numpy=array([[1, 1, 1, 1]], dtype=int32)>}

In [ ]:
tokenizer('hello world', return_tensors='pt')

{'input_ids': tensor([[ 101, 7592, 2088,  102]]), 'token_type_ids': tensor([[0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1]])}

In [6]:
data = ['I love you my you are my cuttiiee!', 'edison born in america']
model_inputs = tokenizer(data)
print(model_inputs)
model_inputs = tokenizer(data,return_tensors='pt', padding=True,truncation=True)
print(model_inputs)

{'input_ids': [[101, 1045, 2293, 2017, 2026, 2017, 2024, 2026, 3013, 3775, 2666, 2063, 999, 102], [101, 17046, 2141, 1999, 2637, 102]], 'token_type_ids': [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0]], 'attention_mask': [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1]]}
{'input_ids': tensor([[  101,  1045,  2293,  2017,  2026,  2017,  2024,  2026,  3013,  3775,
          2666,  2063,   999,   102],
        [  101, 17046,  2141,  1999,  2637,   102,     0,     0,     0,     0,
             0,     0,     0,     0]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0]])}


In [ ]:
from transformers import AutoModelForSequenceClassification

In [ ]:
checkpoint = 'bert-base-uncased' # should be the same as tokenizer
model = AutoModelForSequenceClassification.from_pretrained(checkpoint, num_labels=3)

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [ ]:
outputs = model(**model_inputs)
outputs

SequenceClassifierOutput(loss=None, logits=tensor([[ 0.0878, -0.4002,  0.0113],
        [ 0.1444, -0.3623, -0.0190]], grad_fn=<AddmmBackward0>), hidden_states=None, attentions=None)

In [ ]:
outputs.logits

tensor([[ 0.0878, -0.4002,  0.0113],
        [ 0.1444, -0.3623, -0.0190]], grad_fn=<AddmmBackward0>)

In [ ]:
outputs['logits']

tensor([[ 0.0878, -0.4002,  0.0113],
        [ 0.1444, -0.3623, -0.0190]], grad_fn=<AddmmBackward0>)

In [ ]:
outputs[0]

tensor([[ 0.0878, -0.4002,  0.0113],
        [ 0.1444, -0.3623, -0.0190]], grad_fn=<AddmmBackward0>)

In [ ]:
outputs.logits.detach().cpu().numpy()

array([[ 0.08777933, -0.40021423,  0.01125985],
       [ 0.14439587, -0.36229533, -0.01904628]], dtype=float32)